'use client';
import { useMemo, useState, type ReactNode } from 'react';
import { BarChart3, FileText, CalendarClock, Eye, ArrowLeft, Trash2, Search, Landmark, Briefcase, Cog } from 'lucide-react';
import { useApp } from '@/lib/store';
import { useCtx } from '@/components/dash/hooks';
import * as A from '@/lib/analytics';
import { byId, docTotals, billOpen } from '@/lib/db';
import { trialBalance, generalLedger } from '@/lib/core/ledger';
import { ACC, CHART } from '@/lib/core/coa';
import { fmtDate, TODAY, monthLabel, monthKey } from '@/lib/core/dates';
import { PageHeader, Card, CardHeader, Button, Badge, Modal, Field, Input, Select, cx, DemoTag, Segmented, Empty, SearchInput } from '@/components/ui';
import { DataTable, type Col } from '@/components/ui/DataTable';
import { ExportButton } from '@/components/ui/Export';
import { PnL, BS, CF } from './Statements';
import { can } from '@/lib/rbac';
import type { Column, Row } from '@/lib/exporter';

interface ReportDef { id: string; group: 'financial' | 'management' | 'operational'; title: string; desc: string; render: () => ReactNode }

function Tabular<T>({ title, rows, cols, exportCols, exportRows, module = 'reports' }: { title: string; rows: T[]; cols: Col<T>[]; exportCols: Column[]; exportRows: () => Row[]; module?: 'reports' }) {
  return <Card><CardHeader title={title} actions={<ExportButton module={module} name={title.toLowerCase().replace(/\s+/g, '-')} title={title} cols={exportCols} rows={exportRows} />} /><DataTable rows={rows} rowKey={(r) => JSON.stringify(r).slice(0, 80) + Math.random()} cols={cols} pageSize={15} dense /></Card>;
}

function useReports(): ReportDef[] {
  const { db, s, from, to, m, mf } = useCtx();
  return [
    { id: 'bs', group: 'financial', title: 'Buxgalteriya balansi', desc: 'Aktivlar, majburiyatlar va kapital holati', render: () => <BS /> },
    { id: 'pnl', group: 'financial', title: 'Foyda va zarar (P&L)', desc: 'Tushum, tannarx, xarajatlar va sof foyda — solishtirma davr bilan', render: () => <PnL /> },
    { id: 'cf', group: 'financial', title: 'Pul oqimlari hisoboti', desc: 'Operatsion, investitsion, moliyaviy faoliyat (to‘g‘ridan-to‘g‘ri usul)', render: () => <CF /> },
    { id: 'tb', group: 'financial', title: 'Aylanma-saldo vedomosti', desc: 'Hisoblar bo‘yicha qoldiq va aylanmalar', render: () => { const tb = trialBalance(db.entries, s, from, to); return <Tabular title="Aylanma-saldo vedomosti" rows={tb.rows} cols={[{ key: 'c', header: 'Hisob', primary: true, cell: (r) => `${r.code} ${r.name}` }, { key: 'od', header: 'Boshl. Dt', align: 'right', cell: (r) => (r.openDr ? mf(r.openDr) : '') }, { key: 'oc', header: 'Boshl. Kt', align: 'right', cell: (r) => (r.openCr ? mf(r.openCr) : '') }, { key: 'td', header: 'Aylanma Dt', align: 'right', cell: (r) => (r.turnDr ? mf(r.turnDr) : '') }, { key: 'tc', header: 'Aylanma Kt', align: 'right', cell: (r) => (r.turnCr ? mf(r.turnCr) : '') }, { key: 'cd', header: 'Yakun Dt', align: 'right', cell: (r) => (r.closeDr ? mf(r.closeDr) : '') }, { key: 'cc', header: 'Yakun Kt', align: 'right', cell: (r) => (r.closeCr ? mf(r.closeCr) : '') }]} exportCols={[{ key: 'code', label: 'Hisob' }, { key: 'name', label: 'Nomi' }, { key: 'openDr', label: 'Boshl Dt', type: 'money' }, { key: 'openCr', label: 'Boshl Kt', type: 'money' }, { key: 'turnDr', label: 'Ayl Dt', type: 'money' }, { key: 'turnCr', label: 'Ayl Kt', type: 'money' }, { key: 'closeDr', label: 'Yakun Dt', type: 'money' }, { key: 'closeCr', label: 'Yakun Kt', type: 'money' }]} exportRows={() => tb.rows as never} />; } },
    { id: 'gl', group: 'financial', title: 'Bosh kitob', desc: 'Tanlangan hisob bo‘yicha barcha yozuvlar', render: () => <GL /> },
    { id: 'ar_aging', group: 'financial', title: 'Debitorlik yoshi', desc: 'Mijozlar kesimida joriy / 1–30 / 31–60 / 60+', render: () => { const ag = A.arAging(db, s); return <Tabular title="Debitorlik yoshi" rows={ag.customers} cols={[{ key: 'c', header: 'Mijoz', primary: true, cell: (r) => r.customer }, { key: 'cur', header: 'Joriy', align: 'right', cell: (r) => m(r.b.current) }, { key: 'd30', header: '1–30', align: 'right', cell: (r) => m(r.b.d30) }, { key: 'd60', header: '31–60', align: 'right', cell: (r) => m(r.b.d60) }, { key: 'd60p', header: '60+', align: 'right', cell: (r) => m(r.b.d60p) }, { key: 't', header: 'Jami', align: 'right', cell: (r) => <b>{m(r.total)}</b> }]} exportCols={[{ key: 'c', label: 'Mijoz' }, { key: 'a', label: 'Joriy', type: 'money' }, { key: 'b', label: '1-30', type: 'money' }, { key: 'd', label: '31-60', type: 'money' }, { key: 'e', label: '60+', type: 'money' }, { key: 't', label: 'Jami', type: 'money' }]} exportRows={() => ag.customers.map((c) => ({ c: c.customer, a: c.b.current, b: c.b.d30, d: c.b.d60, e: c.b.d60p, t: c.total }))} />; } },
    { id: 'ap', group: 'financial', title: 'Kreditorlik hisoboti', desc: 'Ta’minotchilarga qarzlar va muddatlar', render: () => { const ap = A.apSchedule(db, s); return <Tabular title="Kreditorlik hisoboti" rows={ap.rows} cols={[{ key: 's', header: 'Ta’minotchi', primary: true, cell: (r) => r.supplier.name }, { key: 'r', header: 'Hisob', cell: (r) => r.bill.supplierRef }, { key: 'd', header: 'Muddat', cell: (r) => fmtDate(r.bill.dueDate) }, { key: 'o', header: 'Qoldiq', align: 'right', cell: (r) => mf(r.open) }]} exportCols={[{ key: 's', label: 'Ta’minotchi' }, { key: 'r', label: 'Hisob' }, { key: 'd', label: 'Muddat' }, { key: 'o', label: 'Qoldiq', type: 'money' }]} exportRows={() => ap.rows.map((r) => ({ s: r.supplier.name, r: r.bill.supplierRef, d: fmtDate(r.bill.dueDate), o: r.open }))} />; } },
    { id: 'revenue', group: 'management', title: 'Tushum tahlili', desc: 'Filial, kanal va oylar bo‘yicha', render: () => { const br = A.branchProfit(db, s, from, to); return <Tabular title="Tushum tahlili (filiallar)" rows={br} cols={[{ key: 'b', header: 'Filial', primary: true, cell: (r) => r.branch.name }, { key: 'r', header: 'Tushum', align: 'right', cell: (r) => m(r.revenue) }, { key: 'g', header: 'Yalpi foyda', align: 'right', cell: (r) => m(r.gross) }, { key: 'o', header: 'Operatsion xarajat', align: 'right', cell: (r) => m(r.opex) }, { key: 'n', header: 'Sof foyda', align: 'right', cell: (r) => m(r.net) }, { key: 'mg', header: 'Marja', align: 'right', cell: (r) => `${r.margin.toFixed(1)}%` }]} exportCols={[{ key: 'b', label: 'Filial' }, { key: 'r', label: 'Tushum', type: 'money' }, { key: 'g', label: 'Yalpi', type: 'money' }, { key: 'n', label: 'Sof', type: 'money' }]} exportRows={() => br.map((x) => ({ b: x.branch.name, r: x.revenue, g: x.gross, n: x.net }))} />; } },
    { id: 'expenses', group: 'management', title: 'Xarajatlar tahlili', desc: 'Kategoriyalar bo‘yicha xarajatlar', render: () => { const c = A.expenseByCategory(db, s, from, to); return <Tabular title="Xarajatlar tahlili" rows={c} cols={[{ key: 'l', header: 'Kategoriya', primary: true, cell: (r) => r.label }, { key: 'a', header: 'Hisoblar', cell: (r) => <span className="font-mono text-[11px] text-t3">{r.accounts.join(', ')}</span> }, { key: 'v', header: 'Summa', align: 'right', cell: (r) => m(r.amount) }]} exportCols={[{ key: 'l', label: 'Kategoriya' }, { key: 'v', label: 'Summa', type: 'money' }]} exportRows={() => c.map((x) => ({ l: x.label, v: x.amount }))} />; } },
    { id: 'profitability', group: 'management', title: 'Mahsulot rentabelligi', desc: 'Mahsulotlar bo‘yicha yalpi foyda va marja', render: () => { const r = A.productProfit(db, s, from, to); return <Tabular title="Mahsulot rentabelligi" rows={r} cols={[{ key: 'n', header: 'Mahsulot', primary: true, cell: (x) => x.p.name }, { key: 'r', header: 'Tushum', align: 'right', cell: (x) => m(x.revenue) }, { key: 'c', header: 'Tannarx', align: 'right', cell: (x) => m(x.cogs) }, { key: 'g', header: 'Yalpi foyda', align: 'right', cell: (x) => m(x.gross) }, { key: 'mg', header: 'Marja', align: 'right', cell: (x) => `${x.margin.toFixed(1)}%` }]} exportCols={[{ key: 'n', label: 'Mahsulot' }, { key: 'r', label: 'Tushum', type: 'money' }, { key: 'c', label: 'Tannarx', type: 'money' }, { key: 'g', label: 'Yalpi', type: 'money' }, { key: 'm', label: 'Marja', type: 'pct' }]} exportRows={() => r.map((x) => ({ n: x.p.name, r: x.revenue, c: x.cogs, g: x.gross, m: x.margin }))} />; } },
    { id: 'customers', group: 'management', title: 'Mijozlar rentabelligi', desc: 'Tushum, marja va qarzdorlik', render: () => { const r = A.customerProfit(db, s, from, to); return <Tabular title="Mijozlar rentabelligi" rows={r} cols={[{ key: 'n', header: 'Mijoz', primary: true, cell: (x) => x.name }, { key: 'r', header: 'Tushum', align: 'right', cell: (x) => m(x.revenue) }, { key: 'g', header: 'Yalpi foyda', align: 'right', cell: (x) => m(x.gross) }, { key: 'mg', header: 'Marja', align: 'right', cell: (x) => `${x.margin.toFixed(1)}%` }, { key: 'o', header: 'Qarz', align: 'right', cell: (x) => m(x.open) }]} exportCols={[{ key: 'n', label: 'Mijoz' }, { key: 'r', label: 'Tushum', type: 'money' }, { key: 'g', label: 'Yalpi', type: 'money' }, { key: 'o', label: 'Qarz', type: 'money' }]} exportRows={() => r.map((x) => ({ n: x.name, r: x.revenue, g: x.gross, o: x.open }))} />; } },
    { id: 'branches', group: 'management', title: 'Filiallar rentabelligi', desc: 'Toshkent, Samarqand, Buxoro, Chirchiq', render: () => { const br = A.branchProfit(db, s, from, to); return <Tabular title="Filiallar rentabelligi" rows={br} cols={[{ key: 'b', header: 'Filial', primary: true, cell: (r) => r.branch.name }, { key: 'r', header: 'Tushum', align: 'right', cell: (r) => m(r.revenue) }, { key: 'n', header: 'Sof foyda', align: 'right', cell: (r) => m(r.net) }, { key: 'mg', header: 'Marja', align: 'right', cell: (r) => `${r.margin.toFixed(1)}%` }]} exportCols={[{ key: 'b', label: 'Filial' }, { key: 'r', label: 'Tushum', type: 'money' }, { key: 'n', label: 'Sof foyda', type: 'money' }]} exportRows={() => br.map((x) => ({ b: x.branch.name, r: x.revenue, n: x.net }))} />; } },
    { id: 'inventory', group: 'operational', title: 'Ombor qoldiqlari', desc: 'SKU bo‘yicha qoldiq, rezerv va qiymat', render: () => { const r = A.stockRows(db, s); return <Tabular title="Ombor qoldiqlari" rows={r} cols={[{ key: 'n', header: 'Mahsulot', primary: true, cell: (x) => x.p.name }, { key: 'q', header: 'Qoldiq', align: 'right', cell: (x) => `${Math.round(x.qty).toLocaleString('ru-RU')} ${x.p.unit}` }, { key: 'r', header: 'Rezerv', align: 'right', cell: (x) => Math.round(x.reserved) }, { key: 'v', header: 'Qiymat', align: 'right', cell: (x) => mf(x.value) }]} exportCols={[{ key: 'n', label: 'Mahsulot' }, { key: 'q', label: 'Qoldiq', type: 'number' }, { key: 'v', label: 'Qiymat', type: 'money' }]} exportRows={() => r.map((x) => ({ n: x.p.name, q: x.qty, v: x.value }))} />; } },
    { id: 'purchasing', group: 'operational', title: 'Xaridlar hisoboti', desc: 'Ta’minotchilar bo‘yicha xarid va yetkazish', render: () => { const r = A.supplierSpend(db, s, from, to); return <Tabular title="Xaridlar hisoboti" rows={r} cols={[{ key: 'n', header: 'Ta’minotchi', primary: true, cell: (x) => x.name }, { key: 's', header: 'Xarid', align: 'right', cell: (x) => m(x.spend) }, { key: 'b', header: 'Hisoblar', align: 'right', cell: (x) => x.bills }, { key: 'o', header: 'O‘z vaqtida', cell: (x) => `${x.onTime}/${x.deliveries}` }]} exportCols={[{ key: 'n', label: 'Ta’minotchi' }, { key: 's', label: 'Xarid', type: 'money' }]} exportRows={() => r.map((x) => ({ n: x.name, s: x.spend }))} />; } },
    { id: 'sales', group: 'operational', title: 'Sotuvlar reestri', desc: 'Davrdagi barcha savdo buyurtmalari', render: () => { const r = db.salesOrders.filter((o) => A.inScope(s, o.companyId, o.branchId) && o.date >= from && o.date <= to); return <Tabular title="Sotuvlar reestri" rows={r} cols={[{ key: 'no', header: '№', primary: true, cell: (o) => o.no }, { key: 'd', header: 'Sana', cell: (o) => fmtDate(o.date) }, { key: 'c', header: 'Mijoz', cell: (o) => byId(db.parties, o.customerId)?.name }, { key: 't', header: 'Jami', align: 'right', cell: (o) => mf(docTotals(o.lines).total) }, { key: 's', header: 'Holat', cell: (o) => o.status }]} exportCols={[{ key: 'no', label: '№' }, { key: 'd', label: 'Sana' }, { key: 'c', label: 'Mijoz' }, { key: 't', label: 'Jami', type: 'money' }]} exportRows={() => r.map((o) => ({ no: o.no, d: fmtDate(o.date), c: byId(db.parties, o.customerId)?.name, t: docTotals(o.lines).total }))} />; } },
    { id: 'production', group: 'operational', title: 'Ishlab chiqarish hisoboti', desc: 'Ish buyurtmalari, brak va tannarx', render: () => { const r = db.workOrders.filter((w) => s.companyIds.includes(w.companyId) && w.actualEnd && w.actualEnd >= from && w.actualEnd <= to); return <Tabular title="Ishlab chiqarish hisoboti" rows={r} cols={[{ key: 'no', header: '№', primary: true, cell: (w) => w.no }, { key: 'p', header: 'Mahsulot', cell: (w) => byId(db.products, w.productId)?.name }, { key: 'g', header: 'Yaroqli', align: 'right', cell: (w) => w.goodQty }, { key: 's', header: 'Brak', align: 'right', cell: (w) => w.scrapQty }, { key: 'c', header: 'Tannarx', align: 'right', cell: (w) => mf(w.materialCost + w.conversionCost) }, { key: 'u', header: 'Birlik', align: 'right', cell: (w) => mf((w.materialCost + w.conversionCost) / Math.max(1, w.goodQty)) }]} exportCols={[{ key: 'no', label: '№' }, { key: 'p', label: 'Mahsulot' }, { key: 'g', label: 'Yaroqli', type: 'number' }, { key: 's', label: 'Brak', type: 'number' }, { key: 'c', label: 'Tannarx', type: 'money' }]} exportRows={() => r.map((w) => ({ no: w.no, p: byId(db.products, w.productId)?.name, g: w.goodQty, s: w.scrapQty, c: w.materialCost + w.conversionCost }))} />; } },
    { id: 'payroll', group: 'operational', title: 'Ish haqi hisoboti', desc: 'Oylar bo‘yicha fond, soliqlar va to‘lovlar', render: () => { const r = db.payrollRuns.filter((x) => s.companyIds.includes(x.companyId)).slice().reverse(); return <Tabular title="Ish haqi hisoboti" rows={r} cols={[{ key: 'p', header: 'Davr', primary: true, cell: (x) => monthLabel(x.period) }, { key: 'c', header: 'Kompaniya', cell: (x) => byId(db.companies, x.companyId)?.short }, { key: 'g', header: 'Hisoblangan', align: 'right', cell: (x) => mf(x.lines.reduce((a, l) => a + l.gross + l.bonus, 0)) }, { key: 't', header: 'JShDS', align: 'right', cell: (x) => mf(x.lines.reduce((a, l) => a + l.pit, 0)) }, { key: 'n', header: 'Qo‘lga', align: 'right', cell: (x) => mf(x.lines.reduce((a, l) => a + l.net, 0)) }, { key: 's', header: 'Holat', cell: (x) => x.status }]} exportCols={[{ key: 'p', label: 'Davr' }, { key: 'c', label: 'Kompaniya' }, { key: 'g', label: 'Hisoblangan', type: 'money' }, { key: 'n', label: 'Qo‘lga', type: 'money' }]} exportRows={() => r.map((x) => ({ p: x.period, c: byId(db.companies, x.companyId)?.short, g: x.lines.reduce((a, l) => a + l.gross + l.bonus, 0), n: x.lines.reduce((a, l) => a + l.net, 0) }))} />; } },
  ];
}

function GL() {
  const { db, s, from, to, mf } = useCtx(); const [acc, setAcc] = useState('5110');
  const gl = useMemo(() => generalLedger(db.entries, s, acc, from, to), [db, s, acc, from, to]);
  return <Card><CardHeader title={`Bosh kitob: ${acc} ${ACC[acc]?.name}`} subtitle={`Boshlang‘ich ${mf(gl.opening)} → yakuniy ${mf(gl.closing)}`} actions={<><Select className="h-8.5 w-64 text-[12.5px]" value={acc} onChange={(e) => setAcc(e.target.value)}>{CHART.map((a) => <option key={a.code} value={a.code}>{a.code} — {a.name}</option>)}</Select><ExportButton module="reports" name={`bosh-kitob-${acc}`} title={`Bosh kitob ${acc}`} cols={[{ key: 'd', label: 'Sana' }, { key: 'no', label: '№' }, { key: 'm', label: 'Izoh' }, { key: 'dr', label: 'Debet', type: 'money' }, { key: 'cr', label: 'Kredit', type: 'money' }, { key: 'b', label: 'Qoldiq', type: 'money' }]} rows={() => gl.rows.map((r) => ({ d: fmtDate(r.date), no: r.no, m: r.memo, dr: r.debit, cr: r.credit, b: r.balance }))} /></>} /><DataTable rows={[...gl.rows].reverse()} rowKey={(r) => r.entryId + r.debit + r.credit + r.memo} pageSize={15} dense cols={[{ key: 'd', header: 'Sana', cell: (r) => fmtDate(r.date) }, { key: 'no', header: '№', cell: (r) => <span className="font-mono text-[11px]">{r.no}</span> }, { key: 'm', header: 'Izoh', primary: true, cell: (r) => <span className="line-clamp-1">{r.memo}</span> }, { key: 'dr', header: 'Debet', align: 'right', cell: (r) => (r.debit ? mf(r.debit) : '') }, { key: 'cr', header: 'Kredit', align: 'right', cell: (r) => (r.credit ? mf(r.credit) : '') }, { key: 'b', header: 'Qoldiq', align: 'right', cell: (r) => mf(r.balance) }]} /></Card>;
}

const GROUPS = { financial: { l: 'Moliyaviy hisobotlar', i: Landmark }, management: { l: 'Boshqaruv hisobotlari', i: Briefcase }, operational: { l: 'Operatsion hisobotlar', i: Cog } };

export default function Reports() {
  const { db, s } = useCtx(); const { nav, role, dispatch, filters, setFilters } = useApp();
  const reports = useReports();
  const [open, setOpen] = useState<string | null>(nav.params?.report || null); const [q, setQ] = useState(''); const [sched, setSched] = useState<string | null>(null);
  const [sf, setSf] = useState({ frequency: 'monthly', format: 'pdf', recipients: 'gulnora@balans.uz' });
  const r = reports.find((x) => x.id === open);
  if (r) return (
    <div>
      <PageHeader title={r.title} crumbs={['Hisobotlar', GROUPS[r.group].l]} subtitle={<span className="flex items-center gap-2">{r.desc} · {filters.companyId === 'all' ? 'BALANS GROUP' : byId(db.companies, filters.companyId)?.name} · {fmtDate(filters.from)}–{fmtDate(filters.to)} · {filters.currency} <DemoTag /></span>}
        actions={<><Button icon={<ArrowLeft className="h-3.5 w-3.5" />} onClick={() => setOpen(null)}>Kutubxona</Button>{can(role, 'reports', 'export') && <Button icon={<CalendarClock className="h-3.5 w-3.5" />} onClick={() => setSched(r.id)}>Jadvalga qo‘yish</Button>}</>} />
      <Card className="mb-4 !p-3"><div className="flex flex-wrap items-center gap-2 text-[12.5px]"><span className="text-t3">Filtrlar:</span><Select className="h-8 w-auto text-[12px]" value={filters.companyId} onChange={(e) => setFilters({ companyId: e.target.value, branchId: 'all' })}><option value="all">BALANS GROUP</option>{db.companies.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select className="h-8 w-auto text-[12px]" value={filters.branchId} onChange={(e) => setFilters({ branchId: e.target.value })}><option value="all">Barcha filiallar</option>{db.branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</Select><Input type="date" className="h-8 w-auto text-[12px]" value={filters.from} onChange={(e) => setFilters({ from: e.target.value })} /><span className="text-t3">—</span><Input type="date" className="h-8 w-auto text-[12px]" value={filters.to} max={TODAY} onChange={(e) => setFilters({ to: e.target.value })} /><Select className="h-8 w-auto text-[12px]" value={filters.currency} onChange={(e) => setFilters({ currency: e.target.value as 'UZS' })}><option>UZS</option><option>USD</option><option>EUR</option></Select></div></Card>
      {r.render()}
      <ScheduleModal id={sched} onClose={() => setSched(null)} sf={sf} setSf={setSf} onSave={() => { dispatch('report.schedule', { reportId: sched, ...sf }, { success: 'Hisobot jadvalga qo‘yildi (email yuborish integratsiyasi ulanmagan)' }); setSched(null); }} />
    </div>
  );
  const shown = reports.filter((x) => !q || (x.title + x.desc).toLowerCase().includes(q.toLowerCase()));
  return (
    <div>
      <PageHeader title="Hisobotlar markazi" crumbs={['Tahlil']} subtitle="Moliyaviy, boshqaruv va operatsion hisobotlar kutubxonasi — har biri: ko‘rish, filtrlash, eksport (Excel/CSV/PDF), jadvalga qo‘yish" actions={<SearchInput value={q} onChange={setQ} placeholder="Hisobot qidirish…" className="w-64" />} />
      <div className="space-y-6">
        {(Object.keys(GROUPS) as (keyof typeof GROUPS)[]).map((g) => { const items = shown.filter((x) => x.group === g); if (!items.length) return null; const I = GROUPS[g].i; return (
          <div key={g}><p className="mb-2.5 flex items-center gap-2 text-[12px] font-semibold uppercase tracking-wider text-t3"><I className="h-3.5 w-3.5" />{GROUPS[g].l}</p>
            <div className="stagger grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map((x) => { const sc = db.schedules.find((y) => y.reportId === x.id); return (
              <Card key={x.id} hover onClick={() => setOpen(x.id)} className="!p-4"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-accent-soft text-accent"><FileText className="h-4.5 w-4.5" /></div><div className="min-w-0 flex-1"><p className="text-[13.5px] font-semibold text-t1">{x.title}</p><p className="mt-0.5 text-[12px] leading-snug text-t3">{x.desc}</p>{sc && <Badge tone="info" className="mt-1.5"><CalendarClock className="h-3 w-3" />{{ daily: 'Har kuni', weekly: 'Har hafta', monthly: 'Har oy' }[sc.frequency]} · {sc.format.toUpperCase()}</Badge>}</div></div>
                <div className="mt-3 flex gap-1.5 border-t border-line pt-3" onClick={(e) => e.stopPropagation()}><Button size="xs" icon={<Eye className="h-3 w-3" />} onClick={() => setOpen(x.id)}>Ko‘rish</Button>{can(role, 'reports', 'export') && <Button size="xs" variant="ghost" icon={<CalendarClock className="h-3 w-3" />} onClick={() => setSched(x.id)}>Jadval</Button>}</div>
              </Card>
            ); })}</div></div>
        ); })}
        {db.schedules.length > 0 && <Card><CardHeader title="Jadvaldagi hisobotlar" subtitle="Yuborish kanali (email) ulanmagan — jadval sozlamasi saqlanadi" icon={<CalendarClock className="h-4 w-4" />} />{db.schedules.map((x) => <div key={x.id} className="flex items-center gap-3 border-t border-line py-2 text-[12.5px]"><span className="flex-1">{reports.find((y) => y.id === x.reportId)?.title}</span><Badge>{{ daily: 'Har kuni', weekly: 'Har hafta', monthly: 'Har oy' }[x.frequency]}</Badge><Badge>{x.format.toUpperCase()}</Badge><span className="hidden text-t3 sm:inline">{x.recipients}</span>{can(role, 'reports', 'export') && <button onClick={() => dispatch('report.unschedule', { id: x.id }, { success: 'Jadval o‘chirildi' })} className="text-t3 hover:text-neg" aria-label="O‘chirish"><Trash2 className="h-3.5 w-3.5" /></button>}</div>)}</Card>}
      </div>
      <ScheduleModal id={sched} onClose={() => setSched(null)} sf={sf} setSf={setSf} onSave={() => { dispatch('report.schedule', { reportId: sched, ...sf }, { success: 'Hisobot jadvalga qo‘yildi' }); setSched(null); }} />
    </div>
  );
}

function ScheduleModal({ id, onClose, sf, setSf, onSave }: { id: string | null; onClose: () => void; sf: { frequency: string; format: string; recipients: string }; setSf: (x: { frequency: string; format: string; recipients: string }) => void; onSave: () => void }) {
  return (
    <Modal open={!!id} onClose={onClose} size="sm" title="Hisobotni jadvalga qo‘yish" subtitle="Email integratsiyasi ulanmagan — jadval saqlanadi, ammo xat yuborilmaydi" footer={<><Button variant="ghost" onClick={onClose}>Bekor qilish</Button><Button variant="primary" onClick={onSave}>Saqlash</Button></>}>
      <div className="space-y-3"><Field label="Davriylik"><Select value={sf.frequency} onChange={(e) => setSf({ ...sf, frequency: e.target.value })}><option value="daily">Har kuni</option><option value="weekly">Har hafta (dushanba)</option><option value="monthly">Har oy (1-sana)</option></Select></Field><Field label="Format"><Select value={sf.format} onChange={(e) => setSf({ ...sf, format: e.target.value })}><option value="pdf">PDF</option><option value="xls">Excel</option><option value="csv">CSV</option></Select></Field><Field label="Qabul qiluvchilar"><Input value={sf.recipients} onChange={(e) => setSf({ ...sf, recipients: e.target.value })} /></Field></div>
    </Modal>
  );
}
